### ISSUE TITLE
Downloading don't seem to use user-defined path variable

### ISSUE THREAD

**Issue by The1andONLYdave** [enen92/screensaver.atv4#11]
Hi, 
If i download the movies from preferences for saving network data it puts it always inside /storage/emulated/0/Download . It won't store to SMB Mounts and not to usb (/storage/usbdisk).
Maybe usbdisk don't work without requesting permissions first (Android 5), but why does samba not work?

Kodi 16.1 stable, Amazon Fire TV (1. Generation), Android 5

(edit: i can't test if the files get moved after downloading all of them, because of limited storage in Downloadsfolder it won't complete more than 3-5 files.)

**Comment by graysky2** [comment]
Sounds like a permissions issue to me.  Does the user kodi runs as have the linux equivalent of 775 both on your samba share and on the underlying filesystem?  Same question for your USB.

**Comment by The1andONLYdave** [comment]
On the USB Disk i get permission denied to make a new folder after changing (                <setting id="download-folder" type="folder" label="32010" **_option="writeable"_**/>) so it seems like a permission issue there.

On the samba share the user can create a folder in folder selection, the files on the filesystem are owned by shared user and have 777. i can also write files there too.

**Comment by The1andONLYdave** [comment]
I'm new to plugin development and modifying kodi, but shouldn't changing https://github.com/enen92/screensaver.atv4/blob/master/resources/lib/downloader.py#L49 to 
`                localfile = os.path.join("smb://WDMYCLOUD/ubuntu/aerials/atv/",video_file)`
not hardcode the smb-path? it still downloads inside /storage/emulated/0/Download . 

@graysky2 is there a quick and easy way to dump some var's on screen or in a logfile (like adding      log(debug, var2+"logged")      inside the .py's?).

**Comment by graysky2** [comment]
I am not a python person by any means so I can't comment.  While we wait for enen92 to reply, you can work around this manually simply by downloading the needed videos putting them where you want, right?  See the readme in https://github.com/graysky2/xscreensaver-aerial for a simple script to does this with wget (linux util).  I have no idea how Android can or cannot use this but you get the idea.

**Comment by The1andONLYdave** [comment]
I've found a temporary solution - i followed the guide to move kodi to usbdisk (temporary because usb is i bit slower while library updating and scraping with my poor usb sticks ;) ) http://forum.kodi.tv/showthread.php?tid=259327
and can now use /usbdisk/Android/data/org.xbmc.kodi/files/ for the movies, so i can download them from inside kodi too.

One issue i found too: Downloading in this Setup only works with 1.3.0, 1.3.2 seems to think the files already exists in the empty folder. It's enumerating the filenames in the download-window but won't actually start to download and store anything.

Still would love to use my NAS for this :)

**Comment by enen92** [comment]
This is because I am not using `xbmcvfs` module hence the addon does not understand the smb:// or nfs:// paths. This has to wait till ~ the end of the month as all my hardware is being used at the moment for other purposes and I can't simply shut them down to set up a local NAS. But I'll fix it :)

**Comment by enen92** [comment]
New version is already on the official repository (1.3.3): https://github.com/xbmc/repo-scripts/pull/359

This should be fixed (as well as looking for videos on a network share). If for some reason it does not work please report.

Cheers
