### ISSUE TITLE
Video player doesn't use refresh rate adaption setting

### ISSUE THREAD

**Issue by DOCaCola** [enen92/screensaver.atv4#13]
The video player ignores the Settings -> Player -> Videos -> Adjust display refresh rate setting.
With this setting enabled, when the screensaver starts, the TV should switch to 30hz as the atv video is 30fps. Currently the monitor stays at 60hz, which is the default setting chosen in the system settings.
Honoring this setting would lead to lower CPU usage, especially on lower end devices while the screensaver plays. In my case it also leads to issues where the image enhancements of my TV cannot properly handle the 30fps content playing at 60hz resulting in studdering frames.

**Comment by tremby** [comment]
I was under the impression that a monitor refresh rate of 60Hz was totally fine for 30Hz video -- it'd just show each video frame for two refresh cycles of the monitor, which as far as I can tell would end up with exactly the same result as a 30Hz refresh cycle. It's when the monitor refresh rate is not an exact multiple of the video frame rate that you have stuttering issues. I wouldn't have thought it'd have any effect on CPU usage either. Please correct me if I'm wrong about any of this.
