### ISSUE TITLE
Screensavers look to other plugins like playing videos

### ISSUE THREAD

**Issue by tremby** [enen92/screensaver.atv4#15]
[script.kodi.hue.ambilight](https://github.com/mpolednik/script.kodi.hue.ambilight) dims my lights when the screensaver starts, which is far from ideal. Is there any way to avoid this?

**Comment by enen92** [comment]
Guess I have a lot to do in this plugin when I have some free time :)

**Comment by tremby** [comment]
Well presumably it's detecting that a video has started playing. So I'm wondering what sort of signals are sent out when a regular screensaver is sent out, and what signals are sent out when this one starts.

**Comment by enen92** [comment]
It's doable, basically the service addon has to detect the `onScreensaverActivated()` event (https://codedocs.xyz/xbmc/xbmc/group__python__monitor.html#ga12654f86c682619219dd84acb74ae429) and check if the enabled screensaver addon is either screensaver.atv4 our videoscreensaver (I think those are the only screensaver addons that use video). The logic is the same on both screensavers, they just catch the `onScreensaverActivated()` event, perform some action to trigger `onScreensaverDeactivated()`and start the video loop afterwards. So the service has to check for a specific time elapsed between both events (deactivate and playback started). It it helps, I can just define a skin property when the video is started by `screensaver.atv4`and remove it when the playback is stopped. That way, any service addon that executes logic when a video starts can check for the existence of the given property.

**Comment by tremby** [comment]
I take it there's no way to work around it on your end and somehow suppress the "video is playing" signals from getting out?

**Comment by enen92** [comment]
Nop, that can't be controlled through the addon. It just pipes videos to the videoplayer. I can work out on the skin property though. That should be fairly easy to implement on ambilight side.

**Comment by tremby** [comment]
I don't know Kodi plugin development; once you know what's necessary on their end perhaps you could post a message to the ticket I referenced on their repository above? Thanks so much.

**Comment by enen92** [comment]
Yap, I'll have a look. However pretty busy till the end of the month. A pity I don't have a hue myself otherwise I would send the "fix" myself

**Comment by enen92** [comment]
This is fixed on their side

**Comment by tremby** [comment]
Yup. Thanks!
