### ISSUE TITLE
Feature request: use CEC to determine if TV is on or off and stop playing the screensaver if the TV is off

### ISSUE THREAD

**Issue by graysky2** [enen92/screensaver.atv4#20]
Is it possible within python, to query the power on status of the TV over cec?  If so, adding a feature that checks the status before the next apple screensaver/movie is queued to play would be very cool.  If on, play, if off, allow for the kodi-native dim option as if the timeout period defined in #18 was hit.

**Comment by graysky2** [comment]
@enen92 what do you think... feasible?

**Comment by enen92** [comment]
Sorry, unfortunately only three cmds are exposed from kodi to communicate with the display via CEC - activate, deactivate and toggle (switch between states). If it could be achieved, I'd have used it during the last feature request

**Comment by graysky2** [comment]
Thanks for the info.  Feel free to close this or keep it open as a place-holder for the future.
