### ISSUE TITLE
Repeat videos mode always on/not deactivated

### ISSUE THREAD

**Issue by flochy** [enen92/screensaver.atv4#21]
Hi, Excellent work here.

The only issue I have is the plugin activates the loop mode (repeat playlist) and is not deactivated (I'm using Kodi 17.1).
So if I watch a video (movie/serie/etc.) after Aerial has been used, the video will loop on stop/end.

See post : http://forum.kodi.tv/showthread.php?tid=246655&pid=2569071#pid2569071

Any fix possible ?
Cheers !

**Comment by alexandrezia** [comment]
I have the same issue, uninstalled until this gets fixed, it's really annoying

**Comment by graysky2** [comment]
> if I watch a video (movie/serie/etc.) after Aerial has been used, the video will loop on stop/end.

Odd, I do not see this behavior.
```
Time of day for videos = All
Show start notification = On
DMPS = Manual
DPMS action = Stop Video
Manual timeout to activate DPMS = 30
Toggle display off = Off
```

**Comment by camjc** [comment]
I’m seeing this on sbmc on shieldtv. Also uninstalling until fixed fwiw.

**Comment by DOCaCola** [comment]
yes, that was the issue why i had to uninstall aerial a long time ago

**Comment by enen92** [comment]
This issue no longer affects aerial since it now manually controls the loop, not messing with the playlist generic settings.

**Comment by enen92** [comment]
was fixed here: https://github.com/enen92/screensaver.atv4/blob/2c5468fe896d1c723324741e8a36b4e9072848d7/changelog.txt#L5
