### ISSUE TITLE
Tarball name contains superfluous name

### ISSUE THREAD

**Issue by graysky2** [enen92/screensaver.atv4#25]
Can you re-tar the 1.4.2 release?  It unpacks to `screensaver.atv4-screensaver.atv4-1.4.2` when I believe you wanted it to unpack to `screensaver.atv4-1.4.2`

**Comment by enen92** [comment]
I used your previous command :)
Check if the tag is okay to you now

**Comment by graysky2** [comment]
There we go.  Works now.
https://aur.archlinux.org/cgit/aur.git/commit/?h=kodi-addon-screensaver-apple-aerial&id=658303bbf8c9d61ab8c7f8ad65cac328d2a826a6
