### ISSUE TITLE
NEXUS PLAYER - "you need to define a download folder"

### ISSUE THREAD

**Issue by johnadaniels** [enen92/screensaver.atv4#27]
Hello,

Awesome Screen Saver!!!  When I click on "Download Videos", I get a message that says: "you need to define a download folder", I click ok, then go to the top and click", "Download Folder" and have chosen multiple folders and then go back to "Download Videos", but get the same message,: "you need to define a download folder".  

Is there a special folder I should be choosing when I click the Download Folder option?

Thank you!  I have been pulling my hair out on this one.
John

**Comment by enen92** [comment]
you need to confirm by clicking "ok" after setting the folder. Then open the settings again and download videos.
Cheers

**Comment by johnadaniels** [comment]
Wow, that worked, thank you!!!!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
