### ISSUE TITLE
4K/HDR screensavers

### ISSUE THREAD

**Issue by swrobel** [enen92/screensaver.atv4#28]
These were released for the ATV 4k and files are available [here](https://sylvan.apple.com/Aerials/2x/entries.json) although apparently the HDR ones need to have their [fourcc changed](https://github.com/JohnCoates/Aerial/issues/378#issuecomment-332449967) to playback properly (confirmed on my Vero 4k)

**Comment by graysky2** [comment]
@swrobel - Nice find.  Curious that there are only unique ones 9 in total.

**Comment by swrobel** [comment]
Yeah, there may very well be more. I just started digging into this, but the HDR Dubai ones look very nice on my Vero 4k saving the files locally to my box, editing the fourcc, and using the Video Screensaver.

**Comment by graysky2** [comment]
The HDR content looks bad on my monitor editing the fourcc.  If @enen92 implements these, I recommend using some sort of toggle:

1) 1080p or 4k
2) SDR and HDR

**Comment by swrobel** [comment]
Agreed, other people have stated on the thread I linked to for the Mac screensaver app that they look bad on non-HDR displays but I can confirm they look awesome on an HDR-capable TV.

**Comment by graysky2** [comment]
> they look bad on non-HDR displays but I can confirm they look awesome on an HDR-capable TV.

To be clear, that is true after modifying the fourcc value, yes?

**Comment by swrobel** [comment]
Correct, I had to edit the fourcc, otherwise the screen just filled with garbled colored blocks when I tried to playback the file.

**Comment by enen92** [comment]
Nice find. Thanks much for the info.
I'll try to implement this as soon as possible but at the moment I am stuffed with work. If someone can implement and pull request the changes it would speed things up.

Cheers

**Comment by kubedzero** [comment]
https://github.com/enen92/screensaver.atv4/pull/47 Done in this PR. Selectable HDR/4K

**Comment by enen92** [comment]
added in https://github.com/xbmc/repo-scripts/pull/1939
