### ISSUE TITLE
Offline mode still contacts apple servers

### ISSUE THREAD

**Issue by graysky2** [enen92/screensaver.atv4#30]
Screensaver.atv4 seems to be connecting out to apple when it comes on despite my configuring it to use offline files (which are on the filesystem).  I see DNS request that seem to be triggered by the screensaver activation.  The two domains I have in my logs are:
```
a1.phobos.apple.com
a1.phobos-apple.com.akadns.net
```

Using version 1.4.2.

**Comment by enen92** [comment]
Offline mode is suposed to rely the playback on the local stored videos but the main playlist file is still remote that's why you see the request. I can easily change that, making the addon use the local playlist.

**Comment by graysky2** [comment]
Sounds good if you'll make the change.  I believe most users would expect 100% local operation using local files.
