### ISSUE TITLE
was it really neccesary to bump the required python version?

### ISSUE THREAD

**Issue by prof7bit** [enen92/screensaver.atv4#32]
Can't install it on SPMC anymore now, it doesn't even show up in the addon list anymore. All versions up until that last commit worked fine.

**Comment by enen92** [comment]
Yes it is a requirement of the repository (xbmc.python has to match the version in the repo). You can however still install it in lower versions if you manually change the api version and install the zip file. Note that the recent version (krypton) requires skinning api calls not available in other kodi versions (IIRC changes require at least jarvis).

**Comment by prof7bit** [comment]
> Why not upgrade to krypton?

 I can't. On my hardware (cheap chinese MXQ-pro) I can only use SPMC and this is still based on 16.x
