### ISSUE TITLE
change os.path.exists to xbmcvfs.exists

### ISSUE THREAD

**Issue by tknorris** [enen92/screensaver.atv4#9]
Love the screensaver. It's my go to after using just "Dim" for years. I didn't want to stream the videos each time and I didn't have room on my android boxes to store all the mov files. So, a couple of small fixes (too small to fork/pr). In playlist.py there are two os.path.exists() checks (line 77 and 82). If you replace those with xbmcvfs.exists() checks then you can store the mov files on a remote server (e.g. nfs) and they will load properly.

Note, I didn't check to see if the Download function works w/ a remote server since I had already downloaded them.

**Comment by enen92** [comment]
closing this as it is already mentioned here: https://github.com/enen92/screensaver.atv4/issues/11

Thanks for reporting though.
